version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: elt_postgres
    environment:
      POSTGRES_USER: WojciecHag
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sumup
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: